inputs:
  raw_daily_parquet: "data/raw/ohlcv_1d.parquet"
  features_parquet: "data/features/features.parquet"

targets:
  horizons: [1, 7]

cv:
  n_folds: 5
  valid_size: 0.15
  expanding: true

model:
  name: "lgbm"
  params:
    # GPU
    device: gpu
    gpu_platform_id: 0
    gpu_device_id: 0

    # GPU 建議
    max_bin: 255
    min_data_in_bin: 3

    # stability
    min_split_gain: 0.0
    verbosity: -1
    random_state: 42

    # next_7d_return best
    learning_rate: 0.03118071756109899
    num_leaves: 47
    min_child_samples: 8
    subsample: 0.7165906844493942
    colsample_bytree: 0.6592331606003983
    reg_lambda: 0.031119790800285305
    reg_alpha: 0.9493502707790766
    n_estimators: 2736

training:
  targets: ["next_7d_return"]

output:
  models_dir: "artifacts/models"
  oof_dir: "artifacts/oof"
  reports_dir: "artifacts/reports"
